
services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432"  # Corrected port mapping syntax
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres  # Added a space after colon for consistency
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data:
